API-000: Updated unifier script to get the correct version
department-of-veterans-affairs/health-apis-conformance-unifier pull request #46
Opened 2021-06-11 20:17 UTC by jabando-va

The unifier script grabbed the lighthouse-maven-starter version instead of the intended unifier version

2021-06-11 20:40 UTC, jhulbert-va commented on unifier/unifier
> +VERSION=$(grep '<version>' pom.xml | head -2 | tail -1 | sed 's|.*<version>\(.*\)</version>.*|\1|')
Something like this should use the correct directories every time.
```
WORKING_DIR=$(readlink -f $(dirname $0))

VERSION=$(grep -E '<version>' ${WORKING_DIR}/../pom.xml | head -1 | sed 's|.*<version>\(.*\)</version>.*|\1|')
java -jar ${WORKING_DIR}/target/unifier-$VERSION.jar $@
```

2021-06-11 21:15 UTC, jabando-va commented on unifier/unifier
> +VERSION=$(grep '<version>' pom.xml | head -2 | tail -1 | sed 's|.*<version>\(.*\)</version>.*|\1|')
```
WORKING_DIR=$(readlink -f $(dirname $0))

VERSION=$(grep -E '<version>' ${WORKING_DIR}/../pom.xml | head -2 | tail -1 | sed 's|.*<version>\(.*\)</version>.*|\1|')
java -jar ${WORKING_DIR}/target/unifier-$VERSION.jar $@
```
? The grep still grabs the health-apis-parent version as the first thing, unifier second.

2021-06-11 21:23 UTC, jabando-va commented on unifier/unifier
> +VERSION=$(grep '<version>' pom.xml | head -2 | tail -1 | sed 's|.*<version>\(.*\)</version>.*|\1|')
`VERSION=$(grep -E '<version>' ${WORKING_DIR}/../unifier/pom.xml | head -2 | tail -1 | sed 's|.*<version>\(.*\)</version>.*|\1|')`
Also works, it instead grabs lighthouse-maven-starter as the first thing, unifier second

2021-06-11 21:24 UTC, jhulbert-va commented on unifier/unifier
> +VERSION=$(grep '<version>' pom.xml | head -2 | tail -1 | sed 's|.*<version>\(.*\)</version>.*|\1|')
That being the case, you can get rid of the head command and just use tail.

2021-06-11 21:30 UTC, jabando-va commented on unifier/unifier
> +VERSION=$(grep '<version>' pom.xml | head -2 | tail -1 | sed 's|.*<version>\(.*\)</version>.*|\1|')
how would I do that? `head -2` gets the first two entries, `tail -1` chooses the last one

2021-06-14 15:30 UTC, jhulbert-va commented on unifier/unifier
> +VERSION=$(grep '<version>' pom.xml | head -2 | tail -1 | sed 's|.*<version>\(.*\)</version>.*|\1|')
You right. That's probably better. I think the working directory thing should still be added though so that the script can be run from any directory.

2021-06-14 15:42 UTC, bschofield-va requested changes
hol up 1 sec

2021-06-14 15:46 UTC, bschofield-va approved these changes

2021-06-14 15:47 UTC, eclendenning-va approved these changes

2021-06-14 15:54 UTC, merged